version: "3.8"

services:
  motionapp-dc:
    image: hexagun/motionapp:minimal
    working_dir: ~/images
    volumes:
      - ~/images:~/images
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video12:/dev/video12"
      - "/dev/video13:/dev/video13"
    restart: unless-stopped
  
  server-dc:
    image: hexagun/py-server:main
    working_dir: ~/images
    ports:
      - 7000:7000
    volumes:
      - ~/images:~/images
    restart: unless-stopped
    


# /usr/local/lib/python3.8/site-packages/cv2/python-3.8